### ISSUE TITLE
Aerox 9 Wireless

### ISSUE THREAD

**Issue by NightClawZ** [mtadin/steelseries-wireless-battery-tray#18]
Hello, 
Would it be possible to work together to add the Aerox 9 Wireless ? 
Also some outline would help to read the value as my taskbar is black and I see nothing : 
![image](https://user-images.githubusercontent.com/4301769/202873199-49f355ce-d043-4428-bd8c-8e1dde1259f1.png)

**Comment by mtadin** [comment]
I checked today, but unfortunately the [node-hid library used to read the batteries](https://github.com/node-hid/node-hid#devices-node-hid-cannot-read) has a limitation that prevents interacting with mice and keyboards due to security reasons.

As for the icon, it isn't a dynamically changing icon. It is just a static icon, and on hover it displays the percentages in a popup. However, I did still update the icon in the latest release due to me personally having visibility issues with it.
